name: Test Secrets

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print secrets
        run: |
          echo ${{ secrets.DOCKER_USERNAME }}
          echo ${{ secrets.DOCKER_PASSWORD }}
